graph TD
a["Authors"] ==> c["constructor"]
r["Reviewers"] ==> c


r --> ak["addKeywords"]
c ==> ak

a --> sd["submitData"]
ak ==> sd

sd ==> f["findReviewers"]
ra["random gen addr"] --> f
f ==> cv["commitVote"]
r --> cv
cv ==> ev["endVoting"]
ev ==> rv["revealVote"]
r --> rv
rv ==> sp["schieling point"]
sp --> aprove
sp --> reject


